### PR TITLE
fix-water

### PR DESCRIPTION
**Pull request by qiuzy**
this commit fixes water calculation problem.

In my test, MPIDOpenMMPlugin can't integrate with OpenMM 7.5.0 with toppar xml file reading error,
but it is ok with OpenMM 7.4.0.

mpidwater.xml is also modified.

### CODE REVIEW

**Comment by andysim** [comment]
Thank you so much for this!  I really appreciate the fixes.  I am going to pull the code to my laptop and test it out a little bit to try and get it working with OpenMM 7.5.  Thank you also for updating the parameters for SWM6 - the existing file was a silly test that I  put together by combining AMOEBA and TIP3P and I forgot to check the proper MPID/SWM6 files into the repository.

**Comment by qiuzy** [comment]
Update:
There is another way to change file ***python/mpidplugin.i***  :
change from

```
 quadrupole.append(conversion*float(atom.get('qXX', 0.0)))
```
to 
```

quadrupole.append(conversion*float(atom.get('qXY')))
```
that is, remove ",0.0". Otherwise it will give dipole, quadrupole and octupole zero value and make MD simulation failed after running a few hundreds of steps.)

**Comment by qiuzy** [comment]
Hi, Andy. SWM4 water parameters xml file is added in my latest commit. Please check it.

In my test, SWM4 is also ok. I don't know what tests you had?  Would you mind provide your test files so that I can compare it with mine to find the difference??

**Comment by andysim** [comment]
Thank you very much for all your time and help.  I will pull this in now and keep experimenting to try and figure out exactly where the problem is.  Some of the fixes that you suggested above are already in the latest version of the code, so my concern is that we might be working from different versions.  If I pull this in and clean up the examples, it should be easier to ensure that we have the same code and for me to demonstrate the problems I am seeing.  Thanks again!

**Pull request merged**
